<?php

/**
 * PluginPlanFeatureDefinitionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPlanFeatureDefinitionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPlanFeatureDefinitionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPlanFeatureDefinition');
    }
}