<?php

/**
 * PluginPlanFeatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPlanFeatureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPlanFeatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPlanFeature');
    }
}