<?php

/**
 * PluginPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPlan');
    }
}