<?php

/**
 * PluginPlan
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPlan extends BasePlan {

  public static function getPlan($id) {
    return Doctrine_Query::create()->
             from('Plan p')->
             where('p.id = ?', $id)->
             fetchOne();
  }

  public static function getAvailablePlans() {
    $q = Doctrine_Query::create()->
          from('Plan p')->
          where('p.is_private = false')->
          andWhere('p.available_from IS NULL OR p.available_from <= NOW()')->
          andWhere('p.available_until IS NULL OR p.available_until >= NOW()');

    return $q->execute(array(), Doctrine_Core::HYDRATE_RECORD);
  }

  public static function getByCode($category, $code_generic, $code) {
    $q = Doctrine_Query::create()->
           from('Plan p')->
           where('p.category = ?', $category);

    return $q->fetchOne();

  }
}